### ISSUE TITLE
Body bg color doesn't cover the whole page

### ISSUE THREAD

**Issue by shortland** [SBUtltmedia/Marginalia#65]
Body height is being computer dynamic?

**Comment by shortland** [comment]
```css
#text {
    display: flex;
    ...
}
```

should of been:

```css
#text {
    display: none;
    ...
}
```
